"""ai_type add severity column

Revision ID: 12720265d7b9
Revises: e0a21eda29b1
Create Date: 2022-04-06 12:24:38.525229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12720265d7b9'
down_revision = 'e0a21eda29b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_type', sa.Column('severity', sa.Integer(), nullable=False, server_default='50'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_type', 'severity')
    # ### end Alembic commands ###
